/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ProvidersNameRouteImport } from './routes/providers.$name'
import { Route as ProvidersNameIndexRouteImport } from './routes/providers.$name.index'
import { Route as ProvidersNameFunctionsTokenRouteImport } from './routes/providers.$name.functions.$token'
import { Route as ProvidersNameResourcesTokenRouteImport } from './routes/providers.$name.resources.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersNameRoute = ProvidersNameRouteImport.update({
  id: '/providers/$name',
  path: '/providers/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersNameIndexRoute = ProvidersNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersNameRoute,
} as any)
const ProvidersNameFunctionsTokenRoute =
  ProvidersNameFunctionsTokenRouteImport.update({
    id: '/functions/$token',
    path: '/functions/$token',
    getParentRoute: () => ProvidersNameRoute,
  } as any)
const ProvidersNameResourcesTokenRoute =
  ProvidersNameResourcesTokenRouteImport.update({
    id: '/resources/$token',
    path: '/resources/$token',
    getParentRoute: () => ProvidersNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/providers/$name': typeof ProvidersNameRouteWithChildren
  '/providers/$name/': typeof ProvidersNameIndexRoute
  '/providers/$name/functions/$token': typeof ProvidersNameFunctionsTokenRoute
  '/providers/$name/resources/$token': typeof ProvidersNameResourcesTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/providers/$name': typeof ProvidersNameIndexRoute
  '/providers/$name/functions/$token': typeof ProvidersNameFunctionsTokenRoute
  '/providers/$name/resources/$token': typeof ProvidersNameResourcesTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/providers/$name': typeof ProvidersNameRouteWithChildren
  '/providers/$name/': typeof ProvidersNameIndexRoute
  '/providers/$name/functions/$token': typeof ProvidersNameFunctionsTokenRoute
  '/providers/$name/resources/$token': typeof ProvidersNameResourcesTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/providers/$name'
    | '/providers/$name/'
    | '/providers/$name/functions/$token'
    | '/providers/$name/resources/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/providers/$name'
    | '/providers/$name/functions/$token'
    | '/providers/$name/resources/$token'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/providers/$name'
    | '/providers/$name/'
    | '/providers/$name/functions/$token'
    | '/providers/$name/resources/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  ProvidersNameRoute: typeof ProvidersNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$name': {
      id: '/providers/$name'
      path: '/providers/$name'
      fullPath: '/providers/$name'
      preLoaderRoute: typeof ProvidersNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$name/': {
      id: '/providers/$name/'
      path: '/'
      fullPath: '/providers/$name/'
      preLoaderRoute: typeof ProvidersNameIndexRouteImport
      parentRoute: typeof ProvidersNameRoute
    }
    '/providers/$name/functions/$token': {
      id: '/providers/$name/functions/$token'
      path: '/functions/$token'
      fullPath: '/providers/$name/functions/$token'
      preLoaderRoute: typeof ProvidersNameFunctionsTokenRouteImport
      parentRoute: typeof ProvidersNameRoute
    }
    '/providers/$name/resources/$token': {
      id: '/providers/$name/resources/$token'
      path: '/resources/$token'
      fullPath: '/providers/$name/resources/$token'
      preLoaderRoute: typeof ProvidersNameResourcesTokenRouteImport
      parentRoute: typeof ProvidersNameRoute
    }
  }
}

interface ProvidersNameRouteChildren {
  ProvidersNameIndexRoute: typeof ProvidersNameIndexRoute
  ProvidersNameFunctionsTokenRoute: typeof ProvidersNameFunctionsTokenRoute
  ProvidersNameResourcesTokenRoute: typeof ProvidersNameResourcesTokenRoute
}

const ProvidersNameRouteChildren: ProvidersNameRouteChildren = {
  ProvidersNameIndexRoute: ProvidersNameIndexRoute,
  ProvidersNameFunctionsTokenRoute: ProvidersNameFunctionsTokenRoute,
  ProvidersNameResourcesTokenRoute: ProvidersNameResourcesTokenRoute,
}

const ProvidersNameRouteWithChildren = ProvidersNameRoute._addFileChildren(
  ProvidersNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  ProvidersNameRoute: ProvidersNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
